name: TerraformApply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          role-to-assume: arn:aws:iam::905418008126:role/GitHubActionsRole # Replace with your role ARN

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validation
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  approval:
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Request Approval
        uses: hmarr/auto-approve-action@v2

  terraform_apply:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          role-to-assume: arn:aws:iam::<your-account-id>:role/<your-role-name>

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
